# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605124a026ef1f442c6d4b046ed435160bd41138504fcf985e8a894ca696f56bd577eb294134a01bccc3a51da6eb0253da3f5fafb93c8737188ca7b4d97764e5

test:
  secret_key_base: 7d728d1705c52688c2f6755d6c12b4b7f1577e6059ae0093c13f54620b9fccec072d1d4aea33651f29db76e172da5959878b2ea83805a656fb134c74f4996cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
